import Head from 'next/head'
export default function Home() {
  return (
    <div id="bodyy" className="flex flex-col items-center justify-center min-h-screen">
      <Head>
        <title>Binary Bodi</title>
        <link rel="icon" href="/images/fab.ico" />
        <link rel="apple-touch-icon" sizes="180x180" href="/fav144.ico" />
        <link rel="icon" type="image/png" sizes="32x32" href="/fav144.ico" />
        <link rel="icon" type="image/png" sizes="16x16" href="/fav144.ico" />
        <link rel="manifest" href="/site.webmanifest"></link>
        <meta property="og:title" content="BinaryBodi" key="ogtitle" />
        <meta property="og:description" content="A Web3 Social Experiment by streamlining Meta" key="ogdesc" />
        <meta property="og:type" content="website" key="ogtype" />
        <meta property="og:url" content="https://binarybodi.xyz" key="ogurl" />
        <meta property="og:site_name" content="https://binarybodi.xy" key="ogsitename" />
        <meta name="twitter:card" content="summary_large_image" key="twcard" />
        <meta property="twitter:domain" content="BinaryBodi" key="twdomain" />
        <meta property="twitter:url" content="https://twitter.com/binarybodi" key="twurl" />
        <meta name="twitter:title" content="BinaryBodi" key="twtitle" />
        <meta name="twitter:description" content="A Web3 Social Experiment by streamlining Meta " key="twdesc" />
      </Head>

      <div >
        <div >
          <div className="flex items-center justify-between w-full ">
            <a href="/home" className=""><img src="images/2.png" width="70" alt="" className="logo-image" /></a><span></span>
            <nav className="flex flex-wrap flex-row justify-around Poppitandfinchsans ">
              <a href="/home" className="text-2xl Roboto-Thin text-white hover:text-black m-6">Home</a>
              <a href="https://mint.binarybodi.xyz" className="text-2xl Roboto-Thin text-white hover:text-black m-6">Mint</a>
              <a href="/faq" className="text-2xl Roboto-Thin  text-white hover:text-black m-6">FAQ</a>
              <a href="/roadmap" className="text-2xl Roboto-Thin text-white hover:text-black m-6">Roadmap</a>
            </nav>
          </div>
        </div>
      </div>
      <div className="md:w-2/3 w-4/5 " id="about">
        <div className="flex flex-wrap lg:flex-nowrap items-center justify-between	">
          <div className="lg:w-/1 w-/2">
            <br></br>
            <h1 className="text-5xl montserrat text-blau py-5 ">Binary Bodi</h1>
            <br></br>
            <p className="text-3xl text-white   Poppitandfinch">

              Streamlining  Meta
            </p>
            <p className="text-2xl  text-blau Poppitandfinchsans">A Web3 Social Experiment</p>
          </div>

        </div>
        <div id="traits" className="flex flex-wrap justify-around ">
          <div className=" p-4"><img src="images/p1a(1).gif" alt="" width="300px" className="feature-image" layout="responsive" objectFit="contain" /></div>
          <div className="flex flex-col justify-between mx-6 sm:w-1/2 w-4/5 py-6 ">
            <p className="text-blau Montserrat-Light text-2xl">WTF ???</p>
            <p className="text-2xl text-white  items-center justify-between  Poppitandfinch">An intiative to build an open social media platform exclusively for web3

            </p><br></br>
            <p className="text-blau Montserrat-Light text-2xl">How ???</p>
            <p className="text-2xl text-white items-center justify-between Poppitandfinch">By mapping all digital assets to a standalone framework to bridge Shitcoins, NFTs and ENS.

            </p>

          </div>
        </div>
        <div className="flex flex-wrap lg:flex-nowrap items-center justify-between w-full">
          <div className="lg:w-2/2 w-/4">
            <p className="text-blau Poppitandfinchsans text-2xl justify-around">An Alchemy For Bot Less and Rug Free Engagements.</p>
            <p className="text-2xl text-white items-center justify-between Poppitandfinch ">
              A perfect and stealth platform for borderless communication
              between shitposters, gm cults, traders, communities, projects and more. Facilitating Onchain collaboration, engagement and development between multiple statekholders without worrying about Bots and Rugs.
            </p>
          </div>
        </div>

        <div id="gallery" className="  ">


          <br></br><br></br>
          <p className="text-blau Montserrat-Light text-4xl py-3 ">The NFT</p>
          <p className="text-2xl text-white items-center justify-between  Poppitandfinch">A collection of Binary BoDi pfp which is built entirely using Curves and Geometrical Shapes. Each of them are programatically generated by combining 700+ attributes and are sorted randomly to ensure the best provable randomness and rarity. Designed and Curated over a period of 11 months, they exhibit a unique and fresh expereince.


            The combination of features of each Bodi has builds its total rarity score and overall rarity tier. Designed and Curated over a period of 11months, each of the Bodi exhibit a unique and fresh expereince.

          </p>
        </div>
        <div id="traits" className="flex flex-wrap justify-around ">
          <div className=" p-4"><img src="images/wqw.gif" alt="" width="300px" className="feature-image" layout="responsive" objectFit="contain" /></div>

          <div className="flex flex-col justify-between mx-6 sm:w-1/2 w-4/5 py-5 ">

            <p className="text-2xl text-white items-center justify-between Poppitandfinch">An ERC 721 token, with a maximum supply of 7777 NFTs bearing
              a creator royality of 1%, Binary BoDi NFTs will act as a gateway
              towards the BoDi platform. Holders enjoy unparallel beneift of lifelong rewards by Embedding, Hosting and Creating Groups, Communities, Projects and more.
            </p>
          </div>
        </div>
        <div className="lg:w-/2 w-/4 " id="about">
          <p className="text-2xl text-white  Poppitandfinch">
          </p>

          <p className="text-2xl text-white items-center justify-between Poppitandfinch">
            <br></br>                An NFT designed to be the access pass towards the platform. Each
            holder will be considered as an OG and will be rewarded accordingly.



          </p>
          <div id="traits" className="flex flex-wrap justify-around  w-full 	mx-6 py-6">
            <div className="flex flex-wrap lg:flex-nowrap justify-around items-center">
              <img className="lg:w-1/2 w-3/4" img src="images/5bodi.png" alt="" width="780px" className="feature-image" layout="responsive" objectFit="contain" />
            </div>
            <p className="text-2xl text-white justify-around items-center Poppitandfinch">            A framework that facilitates collaboration, development, moderation, and co-creation between various projects, arts, and media. We believe NFTs and digital assets continue to evolve and exist in an inter-connected and interdependent manner, So as can shape and build towards a better Desoc.

            </p>
          </div>
          <br></br>
          <div className="flex items-center justify-between w-full border-b-2	pb-6">
            <a href="/home" className=""><img src="images/2.png" width="70" alt="" className="logo-image" /></a><span></span>
            <nav className="flex flex-wrap flex-row justify-around Poppitandfinchsans">
              <a href="/home" className="text-2xl Poppitandfinchsans text-white hover:text-black m-6">Home</a>
              <a href="https://mint.binarybodi.xyz" className="text-2xl Poppitandfinchsans text-white hover:text-black m-6">Mint</a>
              <a href="faq" className="text-2xl Poppitandfinchsans text-white hover:text-black m-6">FAQ</a>
              <a href="/roadmap" className="text-2xl Poppitandfinchsans text-white hover:text-black m-6">Roadmap</a>
              <a href="/about" className="text-2xl Poppitandfinchsans text-white hover:text-black m-6">About</a>

              <a href="https://linktr.ee/binarybodi" className="text-2xl Poppitandfinchsans text-blau  hover:text-white m-6">Communities</a>

            </nav>
          </div>
        </div>
      </div>
      <p className="text-1xl text-white my-6  Poppitandfinch">All rights granted (c) <span className="text-blau text-1xl Poppitandfinchsans">Binary Bodi </span> Fork it  <a href="https://github.com/binarybodi" className="text-blau text-1xl Poppitandfinchsans">Github </a></p>
    </div>

  )
}
